build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  armhf: ghcr.io/home-assistant/armhf-base:3.19
  armv7: ghcr.io/home-assistant/armv7-base:3.19
  i386: ghcr.io/home-assistant/i386-base:3.19
args:
  CUPS_VERSION: "3.0.0"
labels:
  org.opencontainers.image.title: "CUPS 3 (OpenPrinting)"
  org.opencontainers.image.description: "CUPS 3.x from OpenPrinting source with IPP Everywhere support"
  org.opencontainers.image.source: "https://github.com/98kuwa036/cups3-addon"
  org.opencontainers.image.licenses: "Apache-2.0"
