build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.22
  amd64: ghcr.io/home-assistant/amd64-base:3.22
  armhf: ghcr.io/home-assistant/armhf-base:3.22
  armv7: ghcr.io/home-assistant/armv7-base:3.22
labels:
  org.opencontainers.image.title: "CUPS 3.0 (New Architecture)"
  org.opencontainers.image.description: "CUPS 3.0 Experimental - libcups v3 + PAPPL + cups-local + cups-sharing"
  org.opencontainers.image.source: "https://github.com/98kuwa036/cups3-addon"
  org.opencontainers.image.licenses: "Apache-2.0"
